# -*- coding: utf-8 -*-
"""ddss_list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jmsB3iVgy_DjoIFYEyd-MrioVuuo_q8V
"""

import json
import boto3


# This function utilizes a role and policy allowing s3:ListBucket permissions
# The first phase was to test the role based access by generating a bucket list 
# Next phase is to create a list of objects with the bucket

s3 = boto3.resource('s3')

def lambda_handler(event, context):
    
    bucketlist = []
    
    #Create list of all S3 buckets
    for bucket in s3.buckets.all():
        bucketlist.append(bucket.name)
    
    #Output list
    return {
        "statusCode": 200,
        "body": bucketlist
    }